( BEGIN FILE BellyCarve-back-01.ncTNUM: 11 )
( Lefty:False Nunits:1 )
( cline: 9.733 delta:15.5 )
( start_unit: 3 num_units: 1)
( END FILE BellyCarve-back-01.nc )
( BEGIN FILE BellyCarve-back-04.ncTNUM: 12 )
( Lefty:False Nunits:1 )
( cline: 9.733 delta:15.5 )
( start_unit: 3 num_units: 1)
( END FILE BellyCarve-back-04.nc )
( BEGIN FILE Rear-control-back-01.ncTNUM: 11 )
( Lefty:False Nunits:1 )
( cline: 9.733 delta:15.5 )
( start_unit: 3 num_units: 1)
( END FILE Rear-control-back-01.nc )
( BEGIN FILE Rear-control-back-02.ncTNUM: 3 )
( Lefty:False Nunits:1 )
( cline: 9.733 delta:15.5 )
( start_unit: 3 num_units: 1)
( END FILE Rear-control-back-02.nc )
( BEGIN FILE Rear-control-back-03.ncTNUM: 5 )
( Lefty:False Nunits:1 )
( cline: 9.733 delta:15.5 )
( start_unit: 3 num_units: 1)
( END FILE Rear-control-back-03.nc )
( BEGIN FILE Rear-control-back-05.ncTNUM: 19 )
( Lefty:False Nunits:1 )
( cline: 9.733 delta:15.5 )
( start_unit: 3 num_units: 1)
( END FILE Rear-control-back-05.nc )
